---
- hosts: all
  vars:
    repo_location: ~/Desktop
  tasks:

  - name: cloning Stock Repo and setting up
    git: name="git@github.com:dineshkumar-cse/Stock.git" dest="{{repo_location}}/stock"

  - yum: name=pyenv,pyenv-virtualenv
    when: ansible_os_family != "Darwin"

  - homebrew: name=pyenv,pyenv-virtualenv state=latest
    when: ansible_os_family == "Darwin"

  - shell: "cd {{repo_location}}/stock  && {{ item }}"
    with_items:
    - pyenv install $(cat .py-version)
    - pyenv virtualenv $(cat .py-version) $(cat .python-version)

  - shell: "cd {{repo_location}}/stock && {{ item }}"
    with_items:
    - pip install -r requirements.txt
